Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-1a
      ImageId: ami-096800910c1b781ba  # Replace this with an appropriate AMI ID for your region
      InstanceType: t2.micro
      Tags:
      - Key: Name
        Value: "eyal-ecs-01"
